.gcloudignore, app.yaml, middlewares/authenticate.js
-  Setup `app.yaml` file
- Create `.gitcloudignore`
=> Deployment Setup

docs/swagger.json
Adding register, login, reset password, & user verification auth documentation in swagger
=> Auth Documentation

README.md
=> Adding environment variable explanation in readme.md

docs/swagger.json
=> Update Auth & Airline API

routes/airportRouter.js, routes/flightRouter.js, routes/seatRouter.js
=> Adjust Router For Flight, Airport, Seat

routes/index.js, routes/passengerRouter.js
=> Adjust passenger router

migrations/20240525091126-create-flights.js, models/flights.js
There is a bug in flight migration, because the migration is based on old db structure
=> Fix migration

controllers/seatsController.js, package.json, routes/seatRouter.js
=> Create seat bulkcreate & get seats by flightid

docs/swagger.json
=> Update seats & passenger documentation

controllers/discountController.js, migrations/20240525085833-create-airlines.js, migrations/20240525090720-create-discounts.js, routes/discountRouter.js, routes/index.js, seeders/20240529080152-airline.js, seeders/20240530022921-discount.js
add seeder, controller, router for discount
=> add seeder, controller, router for discount

controllers/authController.js, utils/createToken.js
Add full_name & user_status payload in jwt
=> Fixing jwt data payload 

docs/swagger-example.json
=> Update discount documentation

controllers/userProfileController.js, middlewares/authenticate.js, routes/index.js, routes/userRouter.js
=> Create User Profile API

controllers/bookingController.js
Handle Webhook Pending Payment Notification:
Handle Webhook Success Payment Notification:
Handle Webhook Deny Payment Notification:
=> Integrate Notification With Webhook

controllers/notificationsController.js
=> Modify notification controller

utils/processBooking.js
=> Add title attributes to passenger

controllers/seatsController.js, docs/swagger.json, routes/seatRouter.js
Android team need a spesific code for seat status
1. A => Available
2. U => Unavailable & Locked
New Response :
Documentation :
=> Update Seat Response Based On Android Request

controllers/adminAirlineController.js, controllers/adminFlightController.js, public/assets/css/style.css, routes/adminFlightRouter.js, routes/index.js, views/flight/create.ejs, views/flight/edit.ejs, views/flight/list.ejs, views/footer.ejs, views/head.ejs
Feature:
- Create Flight (Auto Generate Seat)
- Edit Flight
- Read Flight
- Delete Flight (Destroy seat by flight_id)
=> Flight Admin Dashboard Done

controllers/adminNotificationController.js, routes/adminNotificationRouter.js, routes/index.js, views/head.ejs, views/notification/create.ejs, views/notification/edit.ejs, views/notification/list.ejs
- create for notification admin dashboard
- update for notification admin dashboard
- delete for notification admin dashboard
=> CRUD for Notification admin dashboard

controllers/airportController.js
Filter by Airport name
Filter by Airport city
=> Add filter by airport name dan airport city

controllers/flightController.js
Done adding response airline & airport
=> Add airline & airport (departure & arrival)

controllers/bookingController.js, models/booking_details.js
Add passenger response in booking history
=> Add passenger data in booking history response

controllers/bookingController.js, routes/bookingRouter.js
Create Cancel booking
Fixing Webhook
=> Create cancel booking and fix webhook for snap

controllers/bookingController.js
=> Fix cancel booking

controllers/flightController.js
=> Add get flight by departure & arrival airport

controllers/adminDiscountController.js, routes/adminDiscountRouter.js, routes/index.js, views/discount/create.ejs, views/discount/edit.ejs, views/discount/list.ejs, views/head.ejs
-create controllers,routes, and views for adminDiscount
=> adminDiscount

.github/workflows/testing.yml, app.js, controllers/adminAirlineController.js, controllers/adminAuthController.js, controllers/adminDashboardController.js, controllers/adminDiscountController.js, controllers/adminFlightController.js, controllers/adminNotificationController.js, middlewares/authenticateAdmin.js, migrations/20240615101037-create-admins.js, models/admins.js, public/assets/css/admin-style.css, public/assets/css/style.css, routes/adminAirlineRouter.js, routes/adminAuthRouter.js, routes/adminDashboardRouter.js, routes/adminDiscountRouter.js, routes/adminFlightRouter.js, routes/adminNotificationRouter.js, routes/index.js, seeders/20240615102011-admin.js, views/auth/login.ejs, views/dashboard/index.ejs, views/head.ejs
- Add login page
- Add dashboard page
- Add logout logic
- Add Login logic
Preview :
=> Admin Dashboard Login

seeders/20240612232929-airline.js, seeders/20240612235701-airport.js, seeders/20240613112052-discount.js, seeders/20240613112125-notification.js, seeders/20240613112159-seat.js, seeders/20240613112215-flight.js
Update seeder rule only for test env
=> Seeder Rule Update

controllers/bookingController.js, controllers/seatsController.js
Documentation:
Published on postman
=> Add filter by class in get seat by flight id

controllers/flightController.js
=> Add duration and sort by duration in flighcontroller

app.js, middlewares/rateLimiter.js, package.json
=> feat : add ratelimiter
